spring:
  application:
    name:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/sb_study_smj
    username: root
    password: 1q2w3e4r

jwt:
  secret: 9fc03f86c3cee61f9af78371cba3aad1f74dc3cc2ff8fb0e33d3ee42ac6ea655885c9d60094137065de7079cefe87cd4a108e27f1f412332262f9f927f34801a

springdoc:
  swagger-ui:
    path: /doc

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.korit.springboot.entity